from django.db import models

class Hogar(models.Model):
    calificacion = models.DecimalField(max_digits=5, decimal_places=2)
    fecha_postulacion = models.DateField()
    nombres = models.CharField(max_length=100)
    apellidos = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()
    tipo_documento = models.CharField(max_length=20)
    num_documento = models.CharField(max_length=20)
    estado_civil = models.CharField(max_length=20)
    sexo = models.CharField(max_length=10)
    radicado = models.CharField(max_length=50)
    estado_postulacion = models.CharField(max_length=50)
    ingresos = models.DecimalField(max_digits=10, decimal_places=2)
    trabajo = models.CharField(max_length=100)
    direccion = models.CharField(max_length=150)
    barrio = models.CharField(max_length=100)
    email = models.EmailField()
    telefono_celular = models.CharField(max_length=15)
    telefono_fijo = models.CharField(max_length=15, blank=True, null=True)
    estrato = models.IntegerField()
    total_ingresos_nucleo = models.DecimalField(max_digits=10, decimal_places=2)
    tiempo_residencia = models.IntegerField()
    puntaje_sisben = models.DecimalField(max_digits=5, decimal_places=2)
    sistema_salud = models.CharField(max_length=50)
    caja_compensacion = models.CharField(max_length=50)
    fondo_cesantias = models.CharField(max_length=50)
    valor_cesantias = models.DecimalField(max_digits=10, decimal_places=2)
    tiene_ahorros = models.BooleanField(default=False)
    entidad_ahorro_programado = models.CharField(max_length=100, blank=True, null=True)
    valor_ahorro_programado = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    reportado_centrales_riesgo = models.BooleanField(default=False)
    tiene_subsidio = models.BooleanField(default=False)
    subsidio = models.CharField(max_length=100, blank=True, null=True)
    credito_hipotecario = models.BooleanField(default=False)
    valor_credito_hipotecario = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    mi_casa_ya = models.BooleanField(default=False)
    valor_mi_casa_ya = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    empresa = models.CharField(max_length=100, blank=True, null=True)
    direccion_empresa = models.CharField(max_length=150, blank=True, null=True)
    barrio_empresa = models.CharField(max_length=100, blank=True, null=True)
    estado = models.CharField(max_length=50)
    motivo = models.CharField(max_length=200, blank=True, null=True)