# Generated by Django 5.1.6 on 2025-02-24 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jefe_hogar', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('anos_residencia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Miembro')),
                ('es_victima', models.BooleanField(default=False, verbose_name='Es víctima de conflicto')),
                ('es_discapacitado', models.BooleanField(default=False, verbose_name='Tiene discapacidad')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros_hogar', to='vivienda.hogar')),
            ],
        ),
    ]
