# Generated by Django 5.1.6 on 2025-02-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_postulacion', models.DateField()),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_documento', models.CharField(max_length=20)),
                ('num_documento', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=10)),
                ('radicado', models.CharField(max_length=50)),
                ('estado_postulacion', models.CharField(max_length=50)),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trabajo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=150)),
                ('barrio', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono_celular', models.CharField(max_length=15)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('estrato', models.IntegerField()),
                ('total_ingresos_nucleo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_residencia', models.IntegerField()),
                ('puntaje_sisben', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sistema_salud', models.CharField(max_length=50)),
                ('caja_compensacion', models.CharField(max_length=50)),
                ('fondo_cesantias', models.CharField(max_length=50)),
                ('valor_cesantias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiene_ahorros', models.BooleanField(default=False)),
                ('entidad_ahorro_programado', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_ahorro_programado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reportado_centrales_riesgo', models.BooleanField(default=False)),
                ('tiene_subsidio', models.BooleanField(default=False)),
                ('subsidio', models.CharField(blank=True, max_length=100, null=True)),
                ('credito_hipotecario', models.BooleanField(default=False)),
                ('valor_credito_hipotecario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mi_casa_ya', models.BooleanField(default=False)),
                ('valor_mi_casa_ya', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_empresa', models.CharField(blank=True, max_length=150, null=True)),
                ('barrio_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
