# Generated by Django 5.1.6 on 2025-02-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
