# Generated by Django 5.1.6 on 2025-02-27 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogares', '0002_alter_convocatoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hogares.convocatoria')),
            ],
        ),
    ]
