# Generated by Django 5.1.6 on 2025-02-28 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hogares', '0003_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100)),
                ('vereda', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono_celular', models.CharField(max_length=20)),
                ('telefono_celular2', models.CharField(blank=True, max_length=20, null=True)),
                ('distancia_tiempo', models.IntegerField(blank=True, help_text='Tiempo en minutos', null=True)),
                ('distancia_km', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('medio_transporte', models.CharField(blank=True, choices=[('bus', 'Bus'), ('moto', 'Moto'), ('bicicleta', 'Bicicleta')], max_length=100, null=True)),
                ('descripcion_llegada', models.TextField(blank=True, null=True)),
                ('predio_suelo', models.CharField(choices=[('rural', 'Rural'), ('urbano', 'Urbano')], default='rural', max_length=50)),
                ('lugar_construccion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_beneficio', models.CharField(blank=True, max_length=100, null=True)),
                ('modalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('condicion_tenencia', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_inmueble', models.CharField(blank=True, max_length=200, null=True)),
                ('cedula_catastral', models.CharField(blank=True, max_length=100, null=True)),
                ('matricula_inmobiliaria', models.CharField(blank=True, max_length=100, null=True)),
                ('excepcion_postulacion', models.CharField(blank=True, max_length=100, null=True)),
                ('perdida_vivienda', models.CharField(blank=True, max_length=100, null=True)),
                ('subsidio_conflicto', models.CharField(blank=True, max_length=100, null=True)),
                ('acreditacion_tenencia', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='convocatoria',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
